#!/usr/local/bin/python3.13
"""Generate the Unicode 15.1 full case-fold table used by the Worker."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import unicodedata

UNICODE_VERSION = "15.1.0"
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "domain"
    / "casefold-map.generated.ts"
)


def quoted(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def render() -> str:
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise RuntimeError(
            "case-fold generation requires Unicode "
            f"{UNICODE_VERSION}, found {unicodedata.unidata_version}"
        )

    lines = [
        "// Generated by scripts/generate_casefold.py with /usr/local/bin/python3.13.",
        "// Do not edit by hand.",
        "",
        f'export const CASE_FOLD_UNICODE_VERSION = "{UNICODE_VERSION}";',
        "",
        "export const CASE_FOLD_MAP: Readonly<Record<string, string>> = {",
    ]
    for code_point in range(0x110000):
        if 0xD800 <= code_point <= 0xDFFF:
            continue
        character = chr(code_point)
        folded = character.casefold()
        if folded != character:
            lines.append(f"  {quoted(character)}: {quoted(folded)},")
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render()

    if arguments.check:
        if (
            not arguments.output.is_file()
            or arguments.output.read_text(encoding="utf-8") != generated
        ):
            raise SystemExit(f"case-fold map is stale: {arguments.output}")
        return

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
